### ISSUE TITLE
typo in payload (lock := 1, unlock := 0)?

### ISSUE THREAD

**Issue by boaks** [core-wg/attacks-on-coap#13]
[Payload: 0 (Lock)](https://github.com/core-wg/attacks-on-coap/blob/main/draft-ietf-core-attacks-on-coap.md?plain=1#L468)

```
   |       |       |   Payload: 0 (Lock)
```

Guess it should be 

```
   |       |       |   Payload: 1 (Lock)
```

also

[Payload: 1 (Unlock)](https://github.com/core-wg/attacks-on-coap/blob/main/draft-ietf-core-attacks-on-coap.md?plain=1#L501) maybe "Payload: 0 (Unlock)".

**Comment by emanjon** [comment]
Fixed in main
