### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by emanjon** [core-wg/attacks-on-coap#5]
Availability is a required property for secure operation which is a bit different from the other properties of confiedentiality, intergrity, and replay.

Added availability to the introduction, should be discussed in the body as well where appropriate.

**Comment by chrysn** [comment]
AIU this has already been renamed to "blocking attack". Given some other comments (#3, #4), it would be good to highlight
* this is a building block (eg. any delays)
* the selectivity (blocking one message and letting through others)
